export const ErrorCode = {
    MISSING_CREDENTIALS: "MISSING_CREDENTIALS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    NAME_EMPTY: "NAME_EMPTY",
    NAME_TOO_LONG: "NAME_TOO_LONG",
    INVALID_URL: "INVALID_URL",
    INVALID_CATEGORY: "INVALID_CATEGORY",
    INVALID_BODY: "INVALID_BODY",
    INVALID_SYNC_INTERVAL: "INVALID_SYNC_INTERVAL",
    SUBJECT_NOT_FOUND: "SUBJECT_NOT_FOUND",
    MIDTERM_NOT_FOUND: "MIDTERM_NOT_FOUND"
    NO_PERMISSION: "NO_PERMISSION"
} as const;